In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
x=[[1,2,3,4],[6,7,8,9]]
arr1=np.array(x)
print(arr1)


[[1 2 3 4]
 [6 7 8 9]]


In [3]:
arr1.ndim #to know the dimention

2

In [4]:
arr1.shape #gives number of rows and columns

(2, 4)

In [5]:
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3D)
arr3D.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [6]:
arr3D.shape

(2, 2, 2)

In [7]:
print(arr1.dtype)#Type of data

int64


In [8]:
print(np.zeros((3,3)))#zero matrix
print(np.ones((2,2)))#Matrix of ones
print(np.eye(4)) # identity matrix
print(np.arange(1,10,2))
print(np.linspace(0,10,5)) # evenly spaced

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]


# Data types in numpy

In [9]:
import numpy as np 

a=np.array(list(range(10)),dtype=np.float64)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
arrint=np.array(list(range(10)),dtype=np.int32)
print(arrint)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
v=arrint.astype(np.float64) #convert to another data type
print(v)
print(v.dtype) # find what kinnd  of data type

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [13]:
x=['1','2','3','4']
num_string=np.array(x,dtype=np.bytes_)
print(num_string)

[b'1' b'2' b'3' b'4']


In [15]:
num_arry=num_string.astype(np.int32)
print(num_arry)#we can convert array of string to integer type as well

[1 2 3 4]


In [16]:
nums=num_string.astype(a.dtype)
print(nums)#we can also specifically convert them to a previous datatype of an array

[1. 2. 3. 4.]


# Pseudo random number generation

In [17]:
import numpy as np 

samples1=np.random.randn(5)#to generate random numbers
print(samples1)

[-1.53953639  1.35730049  1.35414716 -0.77006946 -1.7988778 ]


In [18]:
np.random.randn()#to generate single value

-0.19077415135430734

In [19]:
smp=np.random.randn(2,3) #rows X columns
print(smp)

[[ 0.77450746 -0.32888556  1.76097237]
 [-1.33004869 -1.05567283  0.05431667]]


In [20]:
smp2=np.random.randn(2,3,3)#higher dimention
print(smp2)

[[[ 0.95843496  0.89751732 -0.52748044]
  [ 1.34624537 -0.75039322 -1.17670837]
  [ 1.68078803  0.49215105 -1.47281114]]

 [[ 0.88632596 -0.80648216 -0.07503026]
  [-2.72760782  0.27522102 -0.45091893]
  [-0.22094746 -1.85109637 -0.03742306]]]


# Indexing and Slicing

In [21]:
array1=np.array(np.arange(20))
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
array1[2]#numpy create a view instead of a copy like list slicing

np.int64(2)

In [23]:
array1[10:20]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
xy=[[1,2,3,4],[6,7,8,9]]
arr1=np.array(xy)
print(arr1[1][3])
print(arr1[1,3])

9
9


In [25]:
print(arr1[:2,3])
print(arr1[:2,1:])
print(arr1[:,0:3])

[4 9]
[[2 3 4]
 [7 8 9]]
[[1 2 3]
 [6 7 8]]


# Boolean Indexing

In [26]:
days=np.array(['Sun','Mon','Tue','Wed','Thu','Fri','Sat','Sun','Thu','Thu'])
print(days)

['Sun' 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun' 'Thu' 'Thu']


In [27]:
data=np.random.rand(10,4)
print(data)

[[0.77662438 0.24594792 0.82798439 0.276611  ]
 [0.84091955 0.87631065 0.74650988 0.48762079]
 [0.46662126 0.77784678 0.78657952 0.55627401]
 [0.9930413  0.44683738 0.50560062 0.32438347]
 [0.20480903 0.44905396 0.74735705 0.99508855]
 [0.76507319 0.54397548 0.58720652 0.30401853]
 [0.56417483 0.79424033 0.04589833 0.34229277]
 [0.07719123 0.55883504 0.43142041 0.70387673]
 [0.63593094 0.06522496 0.47084293 0.32802332]
 [0.29391248 0.75250183 0.35712352 0.35002722]]


In [28]:
days=='Sun'

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [29]:
data[days=='Sun'] # this gives position from source data 2nd and 8th row

array([[0.77662438, 0.24594792, 0.82798439, 0.276611  ],
       [0.07719123, 0.55883504, 0.43142041, 0.70387673]])

In [30]:
data[days=='Sun',1]

array([0.24594792, 0.55883504])

In [31]:
~(days=='Sun') #this sympol used to negate the condition

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True])

In [32]:
mult_cond=(days=='Sun')|(days=='Thu') # | 'or' for multiple condition
print(mult_cond)

[ True False False False  True False False  True  True  True]


# Mathematical and Statistical Method

In [33]:
data=np.random.randn(6,3)
data

array([[ 0.76937873,  0.27064293,  0.6448064 ],
       [-0.63714254,  0.11944411,  1.76625579],
       [-0.25489023, -0.12186327,  0.0897037 ],
       [ 0.12364847,  1.23983852,  0.01937203],
       [ 1.36531199,  0.50796917,  0.14726341],
       [-0.26595234, -0.53948703,  0.69689362]])

In [34]:
data.mean()

np.float64(0.3300663035779864)

In [35]:
data.min()

np.float64(-0.6371425358368105)

In [36]:
data.max()

np.float64(1.7662557898371645)

In [37]:
data.sum()

np.float64(5.941193464403755)

In [38]:
data.sum(axis=0) # 0 for row axix 1 for column axis

array([1.1003541 , 1.47654443, 3.36429494])

In [39]:
data[:,0:1].sum()

np.float64(1.1003540955899536)

In [40]:
data.sum(axis=1)

array([ 1.68482806,  1.24855736, -0.2870498 ,  1.38285902,  2.02054457,
       -0.10854576])

In [41]:
values=np.arange(5)
values

array([0, 1, 2, 3, 4])

In [42]:
values.cumsum() # fibanacci series / cumulative sum

array([ 0,  1,  3,  6, 10])

In [43]:
matrix_array=np.array([np.arange(1,5),np.arange(6,10),np.arange(11,15)])
matrix_array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [44]:
matrix_array.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 7,  9, 11, 13],
       [18, 21, 24, 27]])

In [45]:
matrix_array.cumprod(axis=1)

array([[    1,     2,     6,    24],
       [    6,    42,   336,  3024],
       [   11,   132,  1716, 24024]])

# Arithmetic opertaions

In [46]:
data1=np.array([[1,2,3,4],[5,6,7,8]])
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
data1*data1 #multiplication

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [48]:
data1+data1 #addition

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [49]:
data2=data1*3 #scalar multiplication
data2

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [50]:
1/data1 #division

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [51]:
data1**(2) #square

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [52]:
data3=np.array([[1,2,12,14],[10,11,10,10]])
data3

array([[ 1,  2, 12, 14],
       [10, 11, 10, 10]])

In [53]:
(data1>=data3) #chech each element comparison

array([[ True,  True, False, False],
       [False, False, False, False]])

# Universal Functions

In [54]:
import numpy as np
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [55]:
np.sqrt(data) #square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [56]:
np.exp(data)#exponential

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [57]:
np.max(data)

np.int64(4)

In [58]:
np.min(data)

np.int64(0)

In [59]:
data1=np.random.randn(5)
data1

array([-0.86395467,  1.0151198 ,  1.85164743,  1.43361338, -0.91291998])

In [60]:
data2=np.random.randn(5)
data2

array([ 0.76812114, -2.85453907, -1.64318163,  0.56860386,  0.69700764])

In [61]:
np.maximum(data1,data2)

array([0.76812114, 1.0151198 , 1.85164743, 1.43361338, 0.69700764])

In [62]:
data3=np.random.randn(10)*5
data3

array([ 3.91468813,  6.66181768,  1.02029335, -3.4740325 ,  4.62036724,
        2.87685197, -3.15367608, -6.35488915,  2.219692  ,  2.03667399])

In [63]:
fractional,integral=np.modf(data3)

In [64]:
fractional

array([ 0.91468813,  0.66181768,  0.02029335, -0.4740325 ,  0.62036724,
        0.87685197, -0.15367608, -0.35488915,  0.219692  ,  0.03667399])

In [65]:
integral

array([ 3.,  6.,  1., -3.,  4.,  2., -3., -6.,  2.,  2.])

In [66]:
np.sqrt(np.abs(data3))

array([1.97855708, 2.58104973, 1.01009572, 1.86387567, 2.14950395,
       1.69612852, 1.77585925, 2.52089055, 1.48986308, 1.42712087])

In [67]:
np.square(data3)

array([15.32478312, 44.37981486,  1.04099853, 12.0689018 , 21.3477934 ,
        8.27627727,  9.94567281, 40.38461612,  4.92703255,  4.14804093])

In [68]:
np.rint(data3) # round elements to nearest ineteger

array([ 4.,  7.,  1., -3.,  5.,  3., -3., -6.,  2.,  2.])

In [69]:
np.ceil(data3) # compute ceiling of each elements

array([ 4.,  7.,  2., -3.,  5.,  3., -3., -6.,  3.,  3.])

In [70]:
data4=np.arange(10).reshape(2,5)
data4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
data5=np.arange(5,15).reshape(2,5)
data5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
np.add(data4,data5)

array([[ 5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23]])

In [73]:
np.subtract(data5,data4)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [74]:
np.multiply(data4,data5)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [75]:
np.divide(data4,data5)

array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714]])

In [76]:
np.power(data4,data5) # powers first array elemnts by powering with second array elements as power

array([[             0,              1,            128,           6561,
                262144],
       [       9765625,      362797056,    13841287201,   549755813888,
        22876792454961]])

In [77]:
np.greater(data4,data5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [78]:
np.greater(data5,data4)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Conditional in Numpy


In [79]:
import numpy as np

In [80]:
data_x=np.array(np.arange(5))
data_x

array([0, 1, 2, 3, 4])

In [81]:
data_y=np.array(np.arange(5,10))
data_y

array([5, 6, 7, 8, 9])

In [82]:
cond=np.array([True,False,False,True,True])

In [83]:
result=[(x if c else y) for x,c,y in zip(data_x,cond,data_y) ]
result

[np.int64(0), np.int64(6), np.int64(7), np.int64(3), np.int64(4)]

In [84]:
result_where=np.where(cond,data_x,data_y) # we can use where instead of conditional list comprehension as mentioned above
result

[np.int64(0), np.int64(6), np.int64(7), np.int64(3), np.int64(4)]

In [85]:
data_z=np.random.randn(10,4)
data_z

array([[-0.88545377, -0.76835391,  2.01595738,  0.76178396],
       [-2.67540394,  1.47163426, -1.08019405,  0.03735577],
       [ 0.4032964 ,  0.51736183, -3.05983706,  0.53133296],
       [ 0.06682094,  0.08170348,  1.36786791,  1.13237963],
       [-1.54186483, -0.65299401, -0.53920287,  0.95258514],
       [ 0.15795085, -1.89917808, -0.49011021,  1.34559345],
       [-0.10590574,  0.03908971, -1.93903409, -0.70861732],
       [-0.80132369, -0.34805562, -0.29008428, -0.07229547],
       [-1.54903118,  1.19301207,  0.19821184, -0.19935231],
       [-1.29895644, -0.37924461,  0.16489696,  0.41592858]])

In [86]:
result_2=np.where(data_z>0,5,-5)
result_2

array([[-5, -5,  5,  5],
       [-5,  5, -5,  5],
       [ 5,  5, -5,  5],
       [ 5,  5,  5,  5],
       [-5, -5, -5,  5],
       [ 5, -5, -5,  5],
       [-5,  5, -5, -5],
       [-5, -5, -5, -5],
       [-5,  5,  5, -5],
       [-5, -5,  5,  5]])

In [87]:
result_2=np.where(data_z>0,5,data_z)
result_2

array([[-0.88545377, -0.76835391,  5.        ,  5.        ],
       [-2.67540394,  5.        , -1.08019405,  5.        ],
       [ 5.        ,  5.        , -3.05983706,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-1.54186483, -0.65299401, -0.53920287,  5.        ],
       [ 5.        , -1.89917808, -0.49011021,  5.        ],
       [-0.10590574,  5.        , -1.93903409, -0.70861732],
       [-0.80132369, -0.34805562, -0.29008428, -0.07229547],
       [-1.54903118,  5.        ,  5.        , -0.19935231],
       [-1.29895644, -0.37924461,  5.        ,  5.        ]])

# Sorting in Numpy

In [88]:
import numpy as np

In [89]:
data=np.random.randn(10)
data

array([ 2.21196914,  0.76592361, -0.61196758, -0.93871373,  0.45406211,
        1.95819762,  0.55883303, -0.23728337,  0.2353059 ,  0.75086447])

In [90]:
data.sort()
data  # this will sort inplace 

array([-0.93871373, -0.61196758, -0.23728337,  0.2353059 ,  0.45406211,
        0.55883303,  0.75086447,  0.76592361,  1.95819762,  2.21196914])

In [91]:
np.sort(data) # this will retun a copy of array

array([-0.93871373, -0.61196758, -0.23728337,  0.2353059 ,  0.45406211,
        0.55883303,  0.75086447,  0.76592361,  1.95819762,  2.21196914])

In [92]:
matrix_data=np.random.randn(6,3)
matrix_data

array([[ 0.17388322,  0.27897678, -0.26706888],
       [-0.85562618,  0.00262033,  0.82583479],
       [-1.56600659, -0.26800405,  0.43362242],
       [ 1.27499572,  0.70057409,  0.36951226],
       [-0.06273121, -0.70124295, -0.7920201 ],
       [-0.65142808,  0.77023964,  1.29905724]])

In [93]:
matrix_data.sort(axis=1)
matrix_data

array([[-0.26706888,  0.17388322,  0.27897678],
       [-0.85562618,  0.00262033,  0.82583479],
       [-1.56600659, -0.26800405,  0.43362242],
       [ 0.36951226,  0.70057409,  1.27499572],
       [-0.7920201 , -0.70124295, -0.06273121],
       [-0.65142808,  0.77023964,  1.29905724]])

In [94]:
matrix_data.sort(axis=0)
matrix_data

array([[-1.56600659, -0.70124295, -0.06273121],
       [-0.85562618, -0.26800405,  0.27897678],
       [-0.7920201 ,  0.00262033,  0.43362242],
       [-0.65142808,  0.17388322,  0.82583479],
       [-0.26706888,  0.70057409,  1.27499572],
       [ 0.36951226,  0.77023964,  1.29905724]])