# load dataset


In [1]:
from sklearn.datasets import load_iris
import pandas as pd
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


# Data Preprocessing

Handling missing values

In [2]:
from sklearn.impute import SimpleImputer #tools to handle missing values
import numpy as np
data=np.array([[1,2],[np.nan,3],[7,6]])
imputer=SimpleImputer(strategy="mean")
clean_data=imputer.fit_transform(data)
print(clean_data)

[[1. 2.]
 [4. 3.]
 [7. 6.]]


Feature scaling (standardisation and Normalization)

In [3]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaled_data=scaler.fit_transform(df)
print(scaled_data[:5])


[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


Encoding Categorical data

In [4]:
from sklearn.preprocessing import LabelEncoder

labels = ["cat", "dog", "fish", "cat"]
encoder=LabelEncoder()
encoded_labels=encoder.fit_transform(labels)
print(encoded_labels)

[0 1 2 0]


# Train ML Models

Linear regression model

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X=df[['sepal length (cm)']]
y=df[['sepal width (cm)']]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) #test_size=0.2 means 20% of your data will be used for testing, and the remaining 80% will be used for training.
# random state It ensures that every time you run the code, you get the same split of training and testing data.

#train model
model=LinearRegression()
model.fit(X_train,y_train)

#predict
y_pred = model.predict(X_test)
print(y_pred[:5])



[[3.04471278]
 [3.06803045]
 [2.95144208]
 [3.05054219]
 [3.00390685]]


Classificaton (Logistic regression )

In [6]:
# from sklearn.linear_model import LogisticRegression

# clf = LogisticRegression()
# clf.fit(X_train, y_train)
# print(clf.predict(X_test[:5]))

Decision Tree

In [7]:
# from sklearn.tree import DecisionTreeClassifier

# tree = DecisionTreeClassifier()
# tree.fit(X_train, y_train)
# print(tree.predict(X_test[:5]))

# Model Evaluation

check model accuracy

In [8]:
# from sklearn.metrics import accuracy_score

# y_pred = clf.predict(X_test)
# print("Accuracy:", accuracy_score(y_test, y_pred))

Confusion matrix

In [9]:
# from sklearn.metrics import confusion_matrix

# print(confusion_matrix(y_test, y_pred))

Cross-validation

In [10]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(clf, X, y, cv=5)
# print(scores.mean())  # Average accuracy
