In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
x=[[1,2,3,4],[6,7,8,9]]
arr1=np.array(x)
print(arr1)


[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
arr1.ndim #to know the dimention

In [ ]:
arr1.shape #gives number of rows and columns

In [ ]:
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3D)
arr3D.ndim

In [ ]:
arr3D.shape

In [ ]:
print(arr1.dtype)#Type of data

In [ ]:
print(np.zeros((3,3)))#zero matrix
print(np.ones((2,2)))#Matrix of ones
print(np.eye(4)) # identity matrix
print(np.arange(1,10,2))
print(np.linspace(0,10,5)) # evenly spaced

# Data types in numpy

In [ ]:
import numpy as np 

a=np.array(list(range(10)),dtype=np.float64)
print(a)

In [ ]:
arrint=np.array(list(range(10)),dtype=np.int32)
print(arrint)

In [ ]:
v=arrint.astype(np.float64) #convert to another data type
print(v)
print(v.dtype) # find what kinnd  of data type

In [ ]:
x=['1','2','3','4']
num_string=np.array(x,dtype=np.string_)
print(num_string)

In [ ]:
num_arry=num_string.astype(np.int32)
print(num_arry)#we can convert array of string to integer type as well

In [ ]:
nums=num_string.astype(a.dtype)
print(nums)#we can also specifically convert them to a previous datatype of an array

# Pseudo random number generation

In [ ]:
import numpy as np 

samples1=np.random.randn(5)#to generate random numbers
print(samples1)

In [ ]:
np.random.randn()#to generate single value

In [ ]:
smp=np.random.randn(2,3) #rows X columns
print(smp)

In [ ]:
smp2=np.random.randn(2,3,3)#higher dimention
print(smp2)

# Indexing and Slicing

In [ ]:
array1=np.array(np.arange(20))
print(array1)

In [ ]:
array1[2]#numpy create a view instead of a copy like list slicing

In [ ]:
array1[10:20]

In [ ]:
xy=[[1,2,3,4],[6,7,8,9]]
arr1=np.array(xy)
print(arr1[1][3])
print(arr1[1,3])

In [ ]:
print(arr1[:2,3])
print(arr1[:2,1:])
print(arr1[:,0:3])

# Boolean Indexing

In [ ]:
days=np.array(['Sun','Mon','Tue','Wed','Thu','Fri','Sat','Sun','Thu','Thu'])
print(days)

In [ ]:
data=np.random.rand(10,4)
print(data)

In [ ]:
days=='Sun'

In [ ]:
data[days=='Sun'] # this gives position from source data 2nd and 8th row

In [ ]:
data[days=='Sun',1]

In [ ]:
~(days=='Sun') #this sympol used to negate the condition

In [ ]:
mult_cond=(days=='Sun')|(days=='Thu') # | 'or' for multiple condition
print(mult_cond)

# Mathematical and Statistical Method

In [ ]:
data=np.random.randn(6,3)
data

In [ ]:
data.mean()

In [ ]:
data.min()

In [ ]:
data.max()

In [ ]:
data.sum()

In [ ]:
data.sum(axis=0) # 0 for row axix 1 for column axis

In [ ]:
data[:,0:1].sum()

In [ ]:
data.sum(axis=1)

In [ ]:
values=np.arange(5)
values

In [ ]:
values.cumsum() # fibanacci series / cumulative sum

In [ ]:
matrix_array=np.array([np.arange(1,5),np.arange(6,10),np.arange(11,15)])
matrix_array

In [ ]:
matrix_array.cumsum(axis=0)

In [ ]:
matrix_array.cumprod(axis=1)

# Arithmetic opertaions

In [ ]:
data1=np.array([[1,2,3,4],[5,6,7,8]])
data1

In [ ]:
data1*data1 #multiplication

In [ ]:
data1+data1 #addition

In [ ]:
data2=data1*3 #scalar multiplication
data2

In [ ]:
1/data1 #division

In [ ]:
data1**(2) #square

In [ ]:
data3=np.array([[1,2,12,14],[10,11,10,10]])
data3

In [ ]:
(data1>=data3) #chech each element comparison

# Universal Functions

In [4]:
import numpy as np
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [ ]:
np.sqrt(data) #square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.exp(data)#exponential

In [ ]:
np.max(data)

In [ ]:
np.min(data)

In [5]:
data1=np.random.randn(5)
data1

array([-0.58243101,  1.77817055, -0.21472935,  0.24998268, -2.93774576])

In [7]:
data2=np.random.randn(5)
data2

array([ 1.23585716,  0.97713497, -3.43479984, -0.08414899, -0.86849404])

In [8]:
np.maximum(data1,data2)

array([ 1.23585716,  1.77817055, -0.21472935,  0.24998268, -0.86849404])

In [9]:
data3=np.random.randn(10)*5
data3

array([ -0.76990689,  10.13923864,  -0.33387076, -10.18045766,
         1.07753877,  15.52850806,   3.17590289,  -5.05545899,
         5.41108872,  -1.39240536])

In [10]:
fractional,integral=np.modf(data3)

In [11]:
fractional

array([-0.76990689,  0.13923864, -0.33387076, -0.18045766,  0.07753877,
        0.52850806,  0.17590289, -0.05545899,  0.41108872, -0.39240536])

In [12]:
integral

array([ -0.,  10.,  -0., -10.,   1.,  15.,   3.,  -5.,   5.,  -1.])

In [13]:
np.sqrt(np.abs(data3))

array([0.87744338, 3.18421711, 0.57781551, 3.19068295, 1.03804565,
       3.9406228 , 1.78210631, 2.24843479, 2.3261747 , 1.18000227])

In [14]:
np.square(data3)

array([5.92756623e-01, 1.02804160e+02, 1.11469684e-01, 1.03641718e+02,
       1.16108980e+00, 2.41134563e+02, 1.00863592e+01, 2.55576656e+01,
       2.92798811e+01, 1.93879268e+00])

In [ ]:
np.rint(data3) # round elements to nearest ineteger

array([ -1.,  10.,  -0., -10.,   1.,  16.,   3.,  -5.,   5.,  -1.])

In [16]:
np.ceil(data3) # compute ceiling of each elements

array([ -0.,  11.,  -0., -10.,   2.,  16.,   4.,  -5.,   6.,  -1.])

In [20]:
data4=np.arange(10).reshape(2,5)
data4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
data5=np.arange(5,15).reshape(2,5)
data5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
np.add(data4,data5)

array([[ 5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23]])

In [24]:
np.subtract(data5,data4)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [25]:
np.multiply(data4,data5)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [26]:
np.divide(data4,data5)

array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714]])

In [28]:
np.power(data4,data5) # powers first array elemnts by powering with second array elements as power

array([[         0,          1,        128,       6561,     262144],
       [   9765625,  362797056,  956385313,          0, 1796636465]])

In [29]:
np.greater(data4,data5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [30]:
np.greater(data5,data4)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Conditional in Numpy


In [31]:
import numpy as np

In [ ]:
data_x=np.array(np.arange(5))
data_x

array([0, 1, 2, 3, 4])

In [33]:
data_y=np.array(np.arange(5,10))
data_y

array([5, 6, 7, 8, 9])

In [34]:
cond=np.array([True,False,False,True,True])

In [35]:
result=[(x if c else y) for x,c,y in zip(data_x,cond,data_y) ]
result

[0, 6, 7, 3, 4]

In [42]:
result_where=np.where(cond,data_x,data_y) # we can use where instead of conditional list comprehension as mentioned above
result

[0, 6, 7, 3, 4]

In [39]:
data_z=np.random.randn(10,4)
data_z

array([[-0.86005245, -0.86493951, -0.74138883,  0.58233999],
       [ 2.37254788,  0.0389929 ,  0.94551377,  0.86043525],
       [-0.91678371,  1.10559118,  0.02676358, -0.39862603],
       [ 0.03173787, -1.1008307 ,  0.72337283, -1.44455562],
       [ 0.36469493,  1.0953233 , -0.43994941,  1.90754222],
       [ 0.88092408, -1.09647774, -0.24275498,  1.2057692 ],
       [-0.49816312, -1.72206285,  0.07845719, -0.8024758 ],
       [-0.50776314,  0.41215448,  1.00033087,  1.61265791],
       [-0.43998729, -0.88570417, -0.10301731,  0.44522397],
       [ 0.38134034, -1.85711825, -1.46960603, -1.39728949]])

In [40]:
result_2=np.where(data_z>0,5,-5)
result_2

array([[-5, -5, -5,  5],
       [ 5,  5,  5,  5],
       [-5,  5,  5, -5],
       [ 5, -5,  5, -5],
       [ 5,  5, -5,  5],
       [ 5, -5, -5,  5],
       [-5, -5,  5, -5],
       [-5,  5,  5,  5],
       [-5, -5, -5,  5],
       [ 5, -5, -5, -5]])

In [41]:
result_2=np.where(data_z>0,5,data_z)
result_2

array([[-0.86005245, -0.86493951, -0.74138883,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.91678371,  5.        ,  5.        , -0.39862603],
       [ 5.        , -1.1008307 ,  5.        , -1.44455562],
       [ 5.        ,  5.        , -0.43994941,  5.        ],
       [ 5.        , -1.09647774, -0.24275498,  5.        ],
       [-0.49816312, -1.72206285,  5.        , -0.8024758 ],
       [-0.50776314,  5.        ,  5.        ,  5.        ],
       [-0.43998729, -0.88570417, -0.10301731,  5.        ],
       [ 5.        , -1.85711825, -1.46960603, -1.39728949]])

# Sorting in Numpy

In [43]:
import numpy as np

In [44]:
data=np.random.randn(10)
data

array([-0.64809464,  0.23756916, -0.79708441,  1.08554614, -0.12647241,
        0.00701161, -1.01737359,  1.06068252,  1.01918159, -0.62314987])

In [ ]:
data.sort()
data  # this will sort inplace 

array([-1.01737359, -0.79708441, -0.64809464, -0.62314987, -0.12647241,
        0.00701161,  0.23756916,  1.01918159,  1.06068252,  1.08554614])

In [50]:
np.sort(data) # this will retun a copy of array

array([-1.01737359, -0.79708441, -0.64809464, -0.62314987, -0.12647241,
        0.00701161,  0.23756916,  1.01918159,  1.06068252,  1.08554614])

In [49]:
matrix_data=np.random.randn(6,3)
matrix_data

array([[-1.44535867, -0.45629099,  0.87752903],
       [ 0.53862691, -0.12392899,  0.7557267 ],
       [-1.85931078,  0.00582964, -1.10065983],
       [ 0.48879584,  0.94368743, -1.16046726],
       [ 0.74442451,  0.70728594,  0.66777029],
       [ 0.91423816, -0.20882763,  2.27600858]])

In [52]:
matrix_data.sort(axis=1)
matrix_data

array([[-1.44535867, -0.45629099,  0.87752903],
       [-0.12392899,  0.53862691,  0.7557267 ],
       [-1.85931078, -1.10065983,  0.00582964],
       [-1.16046726,  0.48879584,  0.94368743],
       [ 0.66777029,  0.70728594,  0.74442451],
       [-0.20882763,  0.91423816,  2.27600858]])

In [53]:
matrix_data.sort(axis=0)
matrix_data

array([[-1.85931078, -1.10065983,  0.00582964],
       [-1.44535867, -0.45629099,  0.74442451],
       [-1.16046726,  0.48879584,  0.7557267 ],
       [-0.20882763,  0.53862691,  0.87752903],
       [-0.12392899,  0.70728594,  0.94368743],
       [ 0.66777029,  0.91423816,  2.27600858]])