In [ ]:
import pandas as pd

df=pd.read_csv('C:/Users/USER/Documents/Github/Machine Learning/datasets/college_student_placement_dataset.csv')

df.head()

College_ID   IQ  Prev_Sem_Result  CGPA  Academic_Performance  \
0    CLG0030  107             6.61  6.28                     8   
1    CLG0061   97             5.52  5.37                     8   
2    CLG0036  109             5.36  5.83                     9   
3    CLG0055  122             5.47  5.75                     6   
4    CLG0004   96             7.91  7.69                     7   

  Internship_Experience  Extra_Curricular_Score  Communication_Skills  \
0                    No                       8                     8   
1                    No                       7                     8   
2                    No                       3                     1   
3                   Yes                       1                     6   
4                    No                       8                    10   

   Projects_Completed Placement  
0                   4        No  
1                   0        No  
2                   1        No  
3                   1        No  
4                   2        No

In [30]:
df.describe()

IQ  Prev_Sem_Result          CGPA  Academic_Performance  \
count  10000.000000     10000.000000  10000.000000          10000.000000   
mean      99.471800         7.535673      7.532379              5.546400   
std       15.053101         1.447519      1.470141              2.873477   
min       41.000000         5.000000      4.540000              1.000000   
25%       89.000000         6.290000      6.290000              3.000000   
50%       99.000000         7.560000      7.550000              6.000000   
75%      110.000000         8.790000      8.770000              8.000000   
max      158.000000        10.000000     10.460000             10.000000   

       Extra_Curricular_Score  Communication_Skills  Projects_Completed  
count            10000.000000          10000.000000        10000.000000  
mean                 4.970900              5.561800            2.513400  
std                  3.160103              2.900866            1.715959  
min                  0.000000              1.000000            0.000000  
25%                  2.000000              3.000000            1.000000  
50%                  5.000000              6.000000            3.000000  
75%                  8.000000              8.000000            4.000000  
max                 10.000000             10.000000            5.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   College_ID              10000 non-null  object 
 1   IQ                      10000 non-null  int64  
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64  
 5   Internship_Experience   10000 non-null  object 
 6   Extra_Curricular_Score  10000 non-null  int64  
 7   Communication_Skills    10000 non-null  int64  
 8   Projects_Completed      10000 non-null  int64  
 9   Placement               10000 non-null  object 
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB


In [32]:
df.dtypes

College_ID                 object
IQ                          int64
Prev_Sem_Result           float64
CGPA                      float64
Academic_Performance        int64
Internship_Experience      object
Extra_Curricular_Score      int64
Communication_Skills        int64
Projects_Completed          int64
Placement                  object
dtype: object

In [33]:
df.isnull().sum()

College_ID                0
IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [34]:
df.columns

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='object')

In [35]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

df['scaled_IQ']=scaler.fit_transform(df[['IQ']])

In [36]:
df.head()

College_ID   IQ  Prev_Sem_Result  CGPA  Academic_Performance  \
0    CLG0030  107             6.61  6.28                     8   
1    CLG0061   97             5.52  5.37                     8   
2    CLG0036  109             5.36  5.83                     9   
3    CLG0055  122             5.47  5.75                     6   
4    CLG0004   96             7.91  7.69                     7   

  Internship_Experience  Extra_Curricular_Score  Communication_Skills  \
0                    No                       8                     8   
1                    No                       7                     8   
2                    No                       3                     1   
3                   Yes                       1                     6   
4                    No                       8                    10   

   Projects_Completed Placement  scaled_IQ  
0                   4        No   0.500135  
1                   0        No  -0.164214  
2                   1        No   0.633004  
3                   1        No   1.496657  
4                   2        No  -0.230648

In [ ]:
X=df.select_dtypes(include='number').drop(['scaled_IQ'],axis=1)
y=df['Internship_Experience']


from sklearn.feature_selection import SelectKBest,chi2
selector=SelectKBest(score_func=chi2,k=5)

selected=selector.fit_transform(X,y)

result=X.columns[selector.get_support()]

print(result)


feature_scores = pd.DataFrame({
    'Feature': X.columns,
    'Score': selector.scores_
}).sort_values(by='Score', ascending=False)

print(feature_scores)

Index(['Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Communication_Skills', 'Projects_Completed'],
      dtype='object')
                  Feature     Score
3    Academic_Performance  9.987957
5    Communication_Skills  6.318638
6      Projects_Completed  1.233217
1         Prev_Sem_Result  0.495266
2                    CGPA  0.452744
4  Extra_Curricular_Score  0.088003
0                      IQ  0.001394


In [42]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model=LogisticRegression(max_iter=1000)
rfe=RFE(estimator=model,n_features_to_select=5)
rfe.fit(X,y)

selected_rfe=X.columns[rfe.support_]

print(list(selected_rfe))


['Prev_Sem_Result', 'CGPA', 'Academic_Performance', 'Communication_Skills', 'Projects_Completed']


In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

rf=RandomForestClassifier()
rf.fit(X,y_encoded)

importance=rf.feature_importances_

important_features=X.columns[importance>0.1]
print(list(important_features))

['IQ', 'Prev_Sem_Result', 'CGPA', 'Extra_Curricular_Score']


In [58]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,recall_score
from sklearn.linear_model import LogisticRegression

X_train,X_test,y_train,y_test=train_test_split(X,y_encoded,test_size=0.2,random_state=44)

model=LogisticRegression(class_weight='balanced')

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

result1=confusion_matrix(y_test,y_pred)
result2=recall_score(y_test,y_pred)

print(result1)
print(result2)

[[604 575]
 [394 427]]
0.5200974421437271


In [57]:
import numpy as np
print(np.unique(y_encoded, return_counts=True))


(array([0, 1]), array([6036, 3964]))


In [59]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score, classification_report

# Initialize the model
nb_model = GaussianNB()

# Fit the model
nb_model.fit(X_train, y_train)

# Predict
y_pred_nb = nb_model.predict(X_test)

# Evaluation
cm = confusion_matrix(y_test, y_pred_nb)
recall = recall_score(y_test, y_pred_nb)
accuracy = accuracy_score(y_test, y_pred_nb)

print("🔍 Naive Bayes Results")
print("Confusion Matrix:\n", cm)
print("Recall Score:", recall)
print("Accuracy Score:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred_nb))


🔍 Naive Bayes Results
Confusion Matrix:
 [[1179    0]
 [ 821    0]]
Recall Score: 0.0
Accuracy Score: 0.5895

Classification Report:
               precision    recall  f1-score   support

           0       0.59      1.00      0.74      1179
           1       0.00      0.00      0.00       821

    accuracy                           0.59      2000
   macro avg       0.29      0.50      0.37      2000
weighted avg       0.35      0.59      0.44      2000



c:\ProgramData\anaconda3\envs\exassaro\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\anaconda3\envs\exassaro\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\anaconda3\envs\exassaro\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result)

In [60]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score, classification_report

# Initialize the model (you can change n_neighbors to tune)
knn_model = KNeighborsClassifier(n_neighbors=5)

# Fit the model
knn_model.fit(X_train, y_train)

# Predict
y_pred_knn = knn_model.predict(X_test)

# Evaluation
cm = confusion_matrix(y_test, y_pred_knn)
recall = recall_score(y_test, y_pred_knn)
accuracy = accuracy_score(y_test, y_pred_knn)

print("🔍 K-Nearest Neighbors Results")
print("Confusion Matrix:\n", cm)
print("Recall Score:", recall)
print("Accuracy Score:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred_knn))


🔍 K-Nearest Neighbors Results
Confusion Matrix:
 [[837 342]
 [585 236]]
Recall Score: 0.2874543239951279
Accuracy Score: 0.5365

Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.71      0.64      1179
           1       0.41      0.29      0.34       821

    accuracy                           0.54      2000
   macro avg       0.50      0.50      0.49      2000
weighted avg       0.51      0.54      0.52      2000

